#
# Makefile for FPGA implementations of ECO32
#

.PHONY:		all clean

all:

clean:
		rm -f *~
		rm -rf xst
		rm -rf _ngo
		rm -rf _xmsgs
		rm -f __ISE_repository_blocks-in-a-row.ise_.lock
		rm -f blocks-in-a-row.bgn
		rm -f blocks-in-a-row.bit
		rm -f blocks-in-a-row.bld
		rm -f blocks-in-a-row.cmd_log
		rm -f blocks-in-a-row.drc
		rm -f blocks-in-a-row.ise_ISE_Backup
		rm -f blocks-in-a-row.lso
		rm -f blocks-in-a-row.ncd
		rm -f blocks-in-a-row.ngc
		rm -f blocks-in-a-row.ngd
		rm -f blocks-in-a-row.ngr
		rm -f blocks-in-a-row.npl_ISE_Backup
		rm -f blocks-in-a-row.ntrc_log
		rm -f blocks-in-a-row.pad
		rm -f blocks-in-a-row.par
		rm -f blocks-in-a-row.pcf
		rm -f blocks-in-a-row.prj
		rm -f blocks-in-a-row.restore
		rm -f blocks-in-a-row.stx
		rm -f blocks-in-a-row.syr
		rm -f blocks-in-a-row.twr
		rm -f blocks-in-a-row.twx
		rm -f blocks-in-a-row.unroutes
		rm -f blocks-in-a-row.ut
		rm -f blocks-in-a-row.xpi
		rm -f blocks-in-a-row.xst
		rm -f blocks-in-a-row_guide.ncd
		rm -f blocks-in-a-row_ise9migration.zip
		rm -f blocks-in-a-row_map.map
		rm -f blocks-in-a-row_map.mrp
		rm -f blocks-in-a-row_map.ncd
		rm -f blocks-in-a-row_map.ngm
		rm -f blocks-in-a-row_pad.csv
		rm -f blocks-in-a-row_pad.txt
		rm -f blocks-in-a-row_prev_built.ngd
		rm -f blocks-in-a-row_summary.html
		rm -f blocks-in-a-row_summary.xml
		rm -f blocks-in-a-row_usage.xml
